### ISSUE TITLE
Email Validation Regex Only Works for Simple Cases

### ISSUE THREAD

**Issue by jsaintrocc** [dubrowin/AWS-Reasonable-Account-Defaults#1]
Hello Shlomo,

The regex for email validation is limited to simple alphanumeric emails without subdomains. I'd suggest using this regex `^[a-zA-Z0-9.*%±]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$` which I found [here](https://www.mailercheck.com/articles/email-validation-javascript). It handles most cases while still validating a properly formatted email. I 
can also submit a PR if you'd like. I tested it in my deployment, and it works.

Thanks for this project,
~James

**Comment by dubrowin** [comment]
Thanks for helping out with this. I actually knew my regex was deficient. I'm currently travelling to re:Invent, but will look into this when I'm back on planet earth next week.

**Comment by dubrowin** [comment]
James, thank you for the pointer. The suggested regex did not actually work for me, but I modified it to:

^[a-zA-Z0-9.*%±+]*@[a-zA-Z0-9.-]*.[a-zA-Z]*$

and this did work for me in testing. I've updated the CloudFormation template to this updated version.

**Comment by jsaintrocc** [comment]
Thanks Shlomo
